### ISSUE TITLE
滑动时数据重叠

### ISSUE THREAD

**Issue by TerminatorSd** [LinSky/v-weekSlider#2]
有个问题，在手机上快速滑动的时候，两周的数据会发生重叠……博主能帮忙解决一下吗

**Comment by TerminatorSd** [comment]
已经解决了，haha~

**Comment by LinSky** [comment]
> 已经解决了，haha~

请告知原因？我是没有重现

**Comment by TerminatorSd** [comment]
我在weekSlider.vue 中修改了两个地方
第一是touchmoveHandle 和touchendHandle 中开头添加了下面的条件，这个条件可以保证上一次滑动还没结束的时候不能继续触发滑动，否则就可能出现两周数据重叠的问题

> // 如果在动画进行中，则不能继续滑动
> if(this.activeIndex === 0 || this.activeIndex === 2) {
>     return;
> }

第二是onTransitionEnd 中if 和else if 的判断条件，去掉了index === 1 的情况

> // 相比源代码，if 判断条件内去掉index === 1 可以防止滑到某一边划不动的情况
> if (this.activeIndex === 2) {

**Comment by LinSky** [comment]
> 我在weekSlider.vue 中修改了两个地方
> 第一是touchmoveHandle 和touchendHandle 中开头添加了下面的条件，这个条件可以保证上一次滑动还没结束的时候不能继续触发滑动，否则就可能出现两周数据重叠的问题
> 
> > // 如果在动画进行中，则不能继续滑动
> > if(this.activeIndex === 0 || this.activeIndex === 2) {
> > return;
> > }
> 
> 第二是onTransitionEnd 中第if 和else if 的判断条件，去掉了index === 1 的情况
> 
> > // 相比源代码，if 判断条件内去掉index === 1 可以防止滑到某一边划不动的情况
> > if (this.activeIndex === 2) {
谢谢您回复！

**Comment by TerminatorSd** [comment]
不谢不谢，要谢谢你提供了这么好用的组件 O(∩_∩)O
