### ISSUE TITLE
点击某一周某一天，滑动到下一周，activeColor还在

### ISSUE THREAD

**Issue by Twinkle999** [LinSky/v-weekSlider#4]
点击到某一天，滑动到下一周，activeColor，activeBgColor还在，这个问题楼主可以解决下吗？
另外，activeColor，activeBgColor的优先级可以高于todatTextColor、todayBgColor吗？我其实想对今天不做特殊处理，但好像不行，楼主可以解答一下我的疑惑吗？

**Comment by LinSky** [comment]
是这样的如果传入的日期是今天， 那么默认是采用todayBgColor，todatTextColor！还有这里的activeBgColor是你传入的defaultDate日期是星期几标记而已，当滑动到下一周后同样会标记默认日期是星期几，点击日期后只是更新了defaultDate。如果你不想对今天做任何标记处理，可以todayBgColor的值先传一个透明度度为0的rgba颜色值，但这个方法会有一个极限情况就是当你点击的日期刚好是今天的是木有任何颜色标记的，后面我会在逻辑里面改一下，不给todayBgColor默认值！在这里说句抱歉，写这个的时候还是没有考虑到更多用户需求，更多的是结合了自己的业务需求。

**Comment by Twinkle999** [comment]
谢谢楼主的耐心解答，要谢谢你给我们提供了那么好的组件。
楼主，我还想问一下能不能做到我这一周选了一天，滚动到下一周或上一周那个标记就消失呢？因为这个标记不只是星期几，还有日期，感觉有歧义。又或者提供一个方法，我来获取到标记的值做一些程序的处理呢？

**Comment by LinSky** [comment]
可以，后续一起弄下！把标记与否开放出来，用户自己决定是否标记

**Comment by theone2008** [comment]
和Twinkle999 有一样的需求！！
